import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { flattenTheme } from '../src/theme/flatten';
import { breakpoints } from '../src/theme/tokens/breakpoints';
import { light } from '../src/theme/tokens/light';
import { dark } from '../src/theme/tokens/dark';

const block = (selector: string, vars: Record<string, string>) =>
  `${selector} {\n${Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join('\n')}\n}\n`;

const bpVars = Object.fromEntries(Object.entries(breakpoints).map(([k, v]) => [`--oc-breakpoint-${k}`, v]));

const css = [
  '/* AUTO-GENERATED by scripts/generate-theme-css.ts. Do not edit by hand. */',
  '/* Run: npm run gen:theme */',
  '/*',
  ' * Tokens are ported 1:1 from the Bruno app themes (src/theme/tokens/light.ts,',
  ' * dark.ts). The full Bruno set is emitted for fidelity and future component',
  ' * reuse, so some variables are not consumed by the docs UI yet — e.g.',
  ' * --oc-notifications-*, --oc-grpc-*, --oc-console-*, --oc-deprecation-warning-*.',
  ' * These are intentional and safe to keep; prune/refine them later if needed.',
  ' */',
  block(':root', bpVars),
  // Light is also the :root default, so colours resolve even if the root has no
  // data-theme attribute (e.g. applyTheme() never ran) — degrades to light
  // instead of unstyled.
  block(':root,\n[data-theme="light"]', flattenTheme(light as unknown as Record<string, unknown>)),
  block('[data-theme="dark"]', flattenTheme(dark as unknown as Record<string, unknown>)),
].join('\n');

const __dirname = dirname(fileURLToPath(import.meta.url));

writeFileSync(resolve(__dirname, '../src/styles/theme.generated.css'), css);
console.log('theme.generated.css written');
